import type { Metadata } from "next";
import { Schibsted_Grotesk, Martian_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LightRays from "@/components/LightRays";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const schibstedGrotesk = Schibsted_Grotesk({
  variable: "--font-schibsted-grotesk",
  subsets: ["latin"],
});

const martianMono = Martian_Mono({
  variable: "--font-martian-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eventra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", schibstedGrotesk.variable, martianMono.variable, "font-mono", jetbrainsMono.variable)}
    >

      <body className="relative min-h-full flex flex-col" suppressHydrationWarning>
        


  <LightRays
    className="absolute inset-0 z-0"
    raysOrigin="top-center-offset"
    raysColor="#5dfeca"
    raysSpeed={0.5}
    lightSpread={0.9}
    rayLength={1.4}
    followMouse={true}
    mouseInfluence={0.02}
    noiseAmount={0}
    distortion={0.01}
    
    pulsating={false}
    fadeDistance={1}
    saturation={1}
/>

        {children}</body>
    </html>
  );
}
