import type { Metadata } from "next";
import { Manrope, Martian_Mono } from "next/font/google";
import "./globals.css";
import CardNav from "@/components/CardNav";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const martianMono = Martian_Mono({
  variable: "--font-martian-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eventra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full ${manrope.variable} ${martianMono.variable}`}>
      <body className="min-h-full bg-[#08070d] font-[var(--font-manrope)] text-[#f7f2e8] antialiased" suppressHydrationWarning>
        <CardNav
          logo="/icons/logo.png"
          logoAlt="Eventra home"
          items={[
            { label: "Home", bgColor: "#1B1722", textColor: "#fff", links: [{ label: "Discover", href: "/#events", ariaLabel: "Discover events" }, { label: "Home", href: "/", ariaLabel: "Eventra home" }] },
            { label: "Events", bgColor: "#2F293A", textColor: "#fff", links: [{ label: "Featured", href: "/#events", ariaLabel: "Featured events" }, { label: "Create event", href: "/events/create", ariaLabel: "Create event" }] },
            { label: "Account", bgColor: "#2F293A", textColor: "#fff", links: [{ label: "My bookings", href: "/#events", ariaLabel: "My bookings" }, { label: "Profile", href: "/events/create", ariaLabel: "Profile" }] },
          ]}
          ease="power2.easeOut"
          menuColor="#000000"
          buttonBgColor="#111111"
          buttonTextColor="#ffffff"
          initialLoadAnimation={false}
        />
        <div className="page-shell">{children}</div>
      </body>
    </html>
  );
}
